language: python
python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq zip
  - sudo pip install pytz

install:
  - wget https://github.com/google/transitfeed/archive/1.2.14.tar.gz -O transitfeed-1.2.14.tar.gz
  - tar xzf transitfeed-1.2.14.tar.gz
  - pushd transitfeed-1.2.14
  - sudo python setup.py install
  - popd
  - pushd gtfs_files
  - zip patco.zip *
  - popd

script: python validate_feed.py

